<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_PelzvzpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.Pelzvzp' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/CommandHandler/Checkout/ChooseShippingMethodHandler.php';

        return $container->privates['.messenger.handler_descriptor.Pelzvzp'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Sylius\Bundle\ApiBundle\CommandHandler\Checkout\ChooseShippingMethodHandler(($container->services['sylius.repository.order'] ?? $container->getSylius_Repository_OrderService()), ($container->services['sylius.repository.shipping_method'] ?? $container->getSylius_Repository_ShippingMethodService()), ($container->services['sylius.repository.shipment'] ?? $container->load('getSylius_Repository_ShipmentService')), ($container->services['sylius.shipping_method_eligibility_checker'] ?? $container->getSylius_ShippingMethodEligibilityCheckerService()), ($container->services['SM\\Factory\\FactoryInterface'] ?? $container->getFactoryInterfaceService())), []);
    }
}
