<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthorizeActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\PayPalPlugin\Payum\Action\AuthorizeAction' shared service.
     *
     * @return \Sylius\PayPalPlugin\Payum\Action\AuthorizeAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Action/ActionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Payum/Action/AuthorizeAction.php';

        return $container->services['Sylius\\PayPalPlugin\\Payum\\Action\\AuthorizeAction'] = new \Sylius\PayPalPlugin\Payum\Action\AuthorizeAction();
    }
}
