<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvailableCountriesProviderInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\PayPalPlugin\Provider\AvailableCountriesProviderInterface' shared service.
     *
     * @return \Sylius\PayPalPlugin\Provider\AvailableCountriesProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Provider/AvailableCountriesProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Provider/AvailableCountriesProvider.php';

        return $container->privates['Sylius\\PayPalPlugin\\Provider\\AvailableCountriesProviderInterface'] = new \Sylius\PayPalPlugin\Provider\AvailableCountriesProvider(($container->services['sylius.repository.country'] ?? $container->load('getSylius_Repository_CountryService')), ($container->services['Sylius\\Component\\Channel\\Context\\ChannelContextInterface'] ?? $container->getChannelContextInterfaceService()));
    }
}
