<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthorizeClientApiInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\PayPalPlugin\Api\AuthorizeClientApiInterface' shared service.
     *
     * @return \Sylius\PayPalPlugin\Api\AuthorizeClientApi
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Api/AuthorizeClientApiInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Api/AuthorizeClientApi.php';

        return $container->privates['Sylius\\PayPalPlugin\\Api\\AuthorizeClientApiInterface'] = new \Sylius\PayPalPlugin\Api\AuthorizeClientApi(($container->privates['Sylius\\PayPalPlugin\\Client\\PayPalClientInterface'] ?? $container->load('getPayPalClientInterfaceService')));
    }
}
