<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsoleColorDiffBundleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Symplify\ConsoleColorDiff\ConsoleColorDiffBundle' shared autowired service.
     *
     * @return \Symplify\ConsoleColorDiff\ConsoleColorDiffBundle
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Bundle/BundleInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Bundle/Bundle.php';
        include_once \dirname(__DIR__, 4).'/vendor/symplify/console-color-diff/src/ConsoleColorDiffBundle.php';

        return $container->services['Symplify\\ConsoleColorDiff\\ConsoleColorDiffBundle'] = new \Symplify\ConsoleColorDiff\ConsoleColorDiffBundle();
    }
}
