<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCancelPayPalCheckoutPaymentActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\PayPalPlugin\Controller\CancelPayPalCheckoutPaymentAction' shared service.
     *
     * @return \Sylius\PayPalPlugin\Controller\CancelPayPalCheckoutPaymentAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Controller/CancelPayPalCheckoutPaymentAction.php';

        return $container->services['Sylius\\PayPalPlugin\\Controller\\CancelPayPalCheckoutPaymentAction'] = new \Sylius\PayPalPlugin\Controller\CancelPayPalCheckoutPaymentAction(($container->privates['Sylius\\PayPalPlugin\\Provider\\PaymentProviderInterface'] ?? $container->load('getPaymentProviderInterfaceService')), ($container->privates['Sylius\\PayPalPlugin\\Manager\\PaymentStateManagerInterface'] ?? $container->load('getPaymentStateManagerInterfaceService')));
    }
}
