<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompleteOrderApiInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\PayPalPlugin\Api\CompleteOrderApiInterface' shared service.
     *
     * @return \Sylius\PayPalPlugin\Api\CompleteOrderApi
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Api/CompleteOrderApiInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Api/CompleteOrderApi.php';

        return $container->privates['Sylius\\PayPalPlugin\\Api\\CompleteOrderApiInterface'] = new \Sylius\PayPalPlugin\Api\CompleteOrderApi(($container->privates['Sylius\\PayPalPlugin\\Client\\PayPalClientInterface'] ?? $container->load('getPayPalClientInterfaceService')));
    }
}
