<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCapturePaymentResolverInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\PayPalPlugin\Resolver\CapturePaymentResolverInterface' shared service.
     *
     * @return \Sylius\PayPalPlugin\Resolver\CapturePaymentResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Resolver/CapturePaymentResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Resolver/CapturePaymentResolver.php';

        return $container->privates['Sylius\\PayPalPlugin\\Resolver\\CapturePaymentResolverInterface'] = new \Sylius\PayPalPlugin\Resolver\CapturePaymentResolver(($container->services['payum'] ?? $container->load('getPayumService')));
    }
}
