<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsoleDifferService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Symplify\ConsoleColorDiff\Console\Output\ConsoleDiffer' shared autowired service.
     *
     * @return \Symplify\ConsoleColorDiff\Console\Output\ConsoleDiffer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symplify/console-color-diff/src/Console/Output/ConsoleDiffer.php';
        include_once \dirname(__DIR__, 4).'/vendor/sebastian/diff/src/Differ.php';
        include_once \dirname(__DIR__, 4).'/vendor/symplify/console-color-diff/src/Console/Formatter/ColorConsoleDiffFormatter.php';

        return $container->services['Symplify\\ConsoleColorDiff\\Console\\Output\\ConsoleDiffer'] = new \Symplify\ConsoleColorDiff\Console\Output\ConsoleDiffer(($container->services['Symfony\\Component\\Console\\Style\\SymfonyStyle'] ?? $container->load('getSymfonyStyleService')), ($container->services['SebastianBergmann\\Diff\\Differ'] ?? ($container->services['SebastianBergmann\\Diff\\Differ'] = new \SebastianBergmann\Diff\Differ())), ($container->services['Symplify\\ConsoleColorDiff\\Console\\Formatter\\ColorConsoleDiffFormatter'] ?? ($container->services['Symplify\\ConsoleColorDiff\\Console\\Formatter\\ColorConsoleDiffFormatter'] = new \Symplify\ConsoleColorDiff\Console\Formatter\ColorConsoleDiffFormatter())));
    }
}
