<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getColorConsoleDiffFormatterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Symplify\ConsoleColorDiff\Console\Formatter\ColorConsoleDiffFormatter' shared autowired service.
     *
     * @return \Symplify\ConsoleColorDiff\Console\Formatter\ColorConsoleDiffFormatter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symplify/console-color-diff/src/Console/Formatter/ColorConsoleDiffFormatter.php';

        return $container->services['Symplify\\ConsoleColorDiff\\Console\\Formatter\\ColorConsoleDiffFormatter'] = new \Symplify\ConsoleColorDiff\Console\Formatter\ColorConsoleDiffFormatter();
    }
}
