<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreatePayPalOrderFromCartActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\PayPalPlugin\Controller\CreatePayPalOrderFromCartAction' shared service.
     *
     * @return \Sylius\PayPalPlugin\Controller\CreatePayPalOrderFromCartAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Controller/CreatePayPalOrderFromCartAction.php';

        return $container->services['Sylius\\PayPalPlugin\\Controller\\CreatePayPalOrderFromCartAction'] = new \Sylius\PayPalPlugin\Controller\CreatePayPalOrderFromCartAction(($container->services['payum'] ?? $container->load('getPayumService')), ($container->services['sylius.repository.order'] ?? $container->getSylius_Repository_OrderService()), ($container->services['SM\\Factory\\FactoryInterface'] ?? $container->getFactoryInterfaceService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['Sylius\\PayPalPlugin\\Provider\\OrderProviderInterface'] ?? $container->load('getOrderProviderInterfaceService')), ($container->privates['Sylius\\PayPalPlugin\\Resolver\\CapturePaymentResolverInterface'] ?? $container->load('getCapturePaymentResolverInterfaceService')));
    }
}
