<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDifferService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'SebastianBergmann\Diff\Differ' shared autowired service.
     *
     * @return \SebastianBergmann\Diff\Differ
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sebastian/diff/src/Differ.php';

        return $container->services['SebastianBergmann\\Diff\\Differ'] = new \SebastianBergmann\Diff\Differ();
    }
}
