<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnableSellerActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\PayPalPlugin\Controller\EnableSellerAction' shared service.
     *
     * @return \Sylius\PayPalPlugin\Controller\EnableSellerAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Controller/EnableSellerAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Enabler/PaymentMethodEnablerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Enabler/PayPalPaymentMethodEnabler.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/Client.php';

        return $container->services['Sylius\\PayPalPlugin\\Controller\\EnableSellerAction'] = new \Sylius\PayPalPlugin\Controller\EnableSellerAction(($container->services['sylius.repository.payment_method'] ?? $container->getSylius_Repository_PaymentMethodService()), new \Sylius\PayPalPlugin\Enabler\PayPalPaymentMethodEnabler(($container->privates['sylius.http_client'] ?? ($container->privates['sylius.http_client'] = new \GuzzleHttp\Client())), 'https://paypal.sylius.com', ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['Sylius\\PayPalPlugin\\Registrar\\SellerWebhookRegistrarInterface'] ?? $container->load('getSellerWebhookRegistrarInterfaceService'))));
    }
}
