<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosOauthServer_CleanCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'fos_oauth_server.clean_command' shared service.
     *
     * @return \FOS\OAuthServerBundle\Command\CleanCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/oauth-server-bundle/Command/CleanCommand.php';

        $container->privates['fos_oauth_server.clean_command'] = $instance = new \FOS\OAuthServerBundle\Command\CleanCommand(($container->privates['fos_oauth_server.access_token_manager.default'] ?? $container->load('getFosOauthServer_AccessTokenManager_DefaultService')), ($container->privates['fos_oauth_server.refresh_token_manager.default'] ?? $container->load('getFosOauthServer_RefreshTokenManager_DefaultService')), ($container->privates['fos_oauth_server.auth_code_manager.default'] ?? $container->load('getFosOauthServer_AuthCodeManager_DefaultService')));

        $instance->setName('fos:oauth-server:clean');

        return $instance;
    }
}
