<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosOauthServer_Controller_TokenService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'fos_oauth_server.controller.token' shared service.
     *
     * @return \FOS\OAuthServerBundle\Controller\TokenController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/oauth-server-bundle/Controller/TokenController.php';

        return $container->services['fos_oauth_server.controller.token'] = new \FOS\OAuthServerBundle\Controller\TokenController(($container->privates['fos_oauth_server.server'] ?? $container->load('getFosOauthServer_ServerService')));
    }
}
