<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListenerRegistryInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\FixturesBundle\Listener\ListenerRegistryInterface' shared service.
     *
     * @return \Sylius\Bundle\FixturesBundle\Listener\ListenerRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Listener/ListenerRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Listener/ListenerRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Listener/ListenerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Listener/AbstractListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Listener/BeforeSuiteListenerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Listener/ORMPurgerListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Listener/BeforeFixtureListenerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Listener/LoggerListener.php';

        $container->services['Sylius\\Bundle\\FixturesBundle\\Listener\\ListenerRegistryInterface'] = $instance = new \Sylius\Bundle\FixturesBundle\Listener\ListenerRegistry();

        $instance->addListener(new \Sylius\Bundle\FixturesBundle\Listener\ORMPurgerListener(($container->services['doctrine'] ?? $container->getDoctrineService())));
        $instance->addListener(($container->services['sylius_fixtures.listener.suite_loader_listener'] ?? $container->load('getSyliusFixtures_Listener_SuiteLoaderListenerService')));
        $instance->addListener(new \Sylius\Bundle\FixturesBundle\Listener\LoggerListener(($container->services['sylius_fixtures.logger'] ?? $container->load('getSyliusFixtures_LoggerService'))));

        return $instance;
    }
}
