<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayPalConfigurationProviderInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\PayPalPlugin\Provider\PayPalConfigurationProviderInterface' shared service.
     *
     * @return \Sylius\PayPalPlugin\Provider\PayPalConfigurationProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Provider/PayPalConfigurationProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Provider/PayPalConfigurationProvider.php';

        return $container->privates['Sylius\\PayPalPlugin\\Provider\\PayPalConfigurationProviderInterface'] = new \Sylius\PayPalPlugin\Provider\PayPalConfigurationProvider(($container->services['sylius.repository.payment_method'] ?? $container->getSylius_Repository_PaymentMethodService()));
    }
}
