<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayPalPaymentMethodNewResourceFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\PayPalPlugin\Factory\PayPalPaymentMethodNewResourceFactory' shared service.
     *
     * @return \Sylius\PayPalPlugin\Factory\PayPalPaymentMethodNewResourceFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Controller/NewResourceFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Factory/PayPalPaymentMethodNewResourceFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Controller/NewResourceFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Onboarding/Processor/OnboardingProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Onboarding/Processor/BasicOnboardingProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/Client.php';

        return $container->privates['Sylius\\PayPalPlugin\\Factory\\PayPalPaymentMethodNewResourceFactory'] = new \Sylius\PayPalPlugin\Factory\PayPalPaymentMethodNewResourceFactory(new \Sylius\Bundle\ResourceBundle\Controller\NewResourceFactory(), new \Sylius\PayPalPlugin\Onboarding\Processor\BasicOnboardingProcessor(($container->privates['sylius.http_client'] ?? ($container->privates['sylius.http_client'] = new \GuzzleHttp\Client())), ($container->privates['Sylius\\PayPalPlugin\\Registrar\\SellerWebhookRegistrarInterface'] ?? $container->load('getSellerWebhookRegistrarInterfaceService')), 'https://paypal.sylius.com'));
    }
}
