<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayWithPayPalFormActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\PayPalPlugin\Controller\PayWithPayPalFormAction' shared service.
     *
     * @return \Sylius\PayPalPlugin\Controller\PayWithPayPalFormAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Controller/PayWithPayPalFormAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Api/IdentityApiInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Api/IdentityApi.php';

        return $container->services['Sylius\\PayPalPlugin\\Controller\\PayWithPayPalFormAction'] = new \Sylius\PayPalPlugin\Controller\PayWithPayPalFormAction(($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), ($container->services['sylius.repository.payment'] ?? $container->load('getSylius_Repository_PaymentService')), ($container->privates['Sylius\\PayPalPlugin\\Provider\\AvailableCountriesProviderInterface'] ?? $container->load('getAvailableCountriesProviderInterfaceService')), ($container->privates['Sylius\\PayPalPlugin\\Api\\CacheAuthorizeClientApiInterface'] ?? $container->load('getCacheAuthorizeClientApiInterfaceService')), new \Sylius\PayPalPlugin\Api\IdentityApi(($container->privates['Sylius\\PayPalPlugin\\Client\\PayPalClientInterface'] ?? $container->load('getPayPalClientInterfaceService'))));
    }
}
