<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayPalClientInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\PayPalPlugin\Client\PayPalClientInterface' shared service.
     *
     * @return \Sylius\PayPalPlugin\Client\PayPalClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Client/PayPalClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Client/PayPalClient.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/Client.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Provider/UuidProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Provider/UuidProvider.php';

        return $container->privates['Sylius\\PayPalPlugin\\Client\\PayPalClientInterface'] = new \Sylius\PayPalPlugin\Client\PayPalClient(($container->privates['sylius.http_client'] ?? ($container->privates['sylius.http_client'] = new \GuzzleHttp\Client())), ($container->services['monolog.logger.paypal'] ?? $container->load('getMonolog_Logger_PaypalService')), ($container->privates['Sylius\\PayPalPlugin\\Provider\\UuidProviderInterface'] ?? ($container->privates['Sylius\\PayPalPlugin\\Provider\\UuidProviderInterface'] = new \Sylius\PayPalPlugin\Provider\UuidProvider())), ($container->privates['Sylius\\PayPalPlugin\\Provider\\PayPalConfigurationProviderInterface'] ?? $container->load('getPayPalConfigurationProviderInterfaceService')), ($container->services['Sylius\\Component\\Channel\\Context\\ChannelContextInterface'] ?? $container->getChannelContextInterfaceService()), 'https://api.sandbox.paypal.com/', 5, false);
    }
}
