<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayPalButtonsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\PayPalPlugin\Controller\PayPalButtonsController' shared service.
     *
     * @return \Sylius\PayPalPlugin\Controller\PayPalButtonsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Controller/PayPalButtonsController.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Processor/LocaleProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Processor/LocaleProcessor.php';

        return $container->services['Sylius\\PayPalPlugin\\Controller\\PayPalButtonsController'] = new \Sylius\PayPalPlugin\Controller\PayPalButtonsController(($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), ($container->services['router'] ?? $container->getRouterService()), ($container->services['Sylius\\Component\\Channel\\Context\\ChannelContextInterface'] ?? $container->getChannelContextInterfaceService()), ($container->services['Sylius\\Component\\Locale\\Context\\LocaleContextInterface'] ?? $container->getLocaleContextInterfaceService()), ($container->privates['Sylius\\PayPalPlugin\\Provider\\PayPalConfigurationProviderInterface'] ?? $container->load('getPayPalConfigurationProviderInterfaceService')), ($container->services['sylius.repository.order'] ?? $container->getSylius_Repository_OrderService()), ($container->privates['Sylius\\PayPalPlugin\\Provider\\AvailableCountriesProviderInterface'] ?? $container->load('getAvailableCountriesProviderInterfaceService')), new \Sylius\PayPalPlugin\Processor\LocaleProcessor());
    }
}
