<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPagerfanta_ViewFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'pagerfanta.view_factory' shared service.
     *
     * @return \Pagerfanta\View\ViewFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Core/View/ViewFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Core/View/ViewFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Core/View/ViewInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Core/View/View.php';
        include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Core/View/TemplateView.php';
        include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Core/View/DefaultView.php';
        include_once \dirname(__DIR__, 4).'/vendor/babdev/pagerfanta-bundle/View/TranslatedView.php';
        include_once \dirname(__DIR__, 4).'/vendor/babdev/pagerfanta-bundle/View/DefaultTranslatedView.php';
        include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Core/View/SemanticUiView.php';
        include_once \dirname(__DIR__, 4).'/vendor/babdev/pagerfanta-bundle/View/SemanticUiTranslatedView.php';
        include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Core/View/TwitterBootstrapView.php';
        include_once \dirname(__DIR__, 4).'/vendor/babdev/pagerfanta-bundle/View/TwitterBootstrapTranslatedView.php';
        include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Core/View/TwitterBootstrap3View.php';
        include_once \dirname(__DIR__, 4).'/vendor/babdev/pagerfanta-bundle/View/TwitterBootstrap3TranslatedView.php';
        include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Core/View/TwitterBootstrap4View.php';
        include_once \dirname(__DIR__, 4).'/vendor/babdev/pagerfanta-bundle/View/TwitterBootstrap4TranslatedView.php';
        include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Core/View/TwitterBootstrap5View.php';
        include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Twig/View/TwigView.php';

        $container->services['pagerfanta.view_factory'] = $instance = new \Pagerfanta\View\ViewFactory();

        $a = new \Pagerfanta\View\DefaultView();
        $b = ($container->services['translator'] ?? $container->getTranslatorService());
        $c = new \Pagerfanta\View\SemanticUiView();
        $d = new \Pagerfanta\View\TwitterBootstrapView();
        $e = new \Pagerfanta\View\TwitterBootstrap3View();
        $f = new \Pagerfanta\View\TwitterBootstrap4View();

        $instance->set('default', $a);
        $instance->set('default_translated', new \BabDev\PagerfantaBundle\View\DefaultTranslatedView($a, $b));
        $instance->set('semantic_ui', $c);
        $instance->set('semantic_ui_translated', new \BabDev\PagerfantaBundle\View\SemanticUiTranslatedView($c, $b));
        $instance->set('twitter_bootstrap', $d);
        $instance->set('twitter_bootstrap_translated', new \BabDev\PagerfantaBundle\View\TwitterBootstrapTranslatedView($d, $b));
        $instance->set('twitter_bootstrap3', $e);
        $instance->set('twitter_bootstrap3_translated', new \BabDev\PagerfantaBundle\View\TwitterBootstrap3TranslatedView($e, $b));
        $instance->set('twitter_bootstrap4', $f);
        $instance->set('twitter_bootstrap4_translated', new \BabDev\PagerfantaBundle\View\TwitterBootstrap4TranslatedView($f, $b));
        $instance->set('twitter_bootstrap5', new \Pagerfanta\View\TwitterBootstrap5View());
        $instance->set('twig', new \Pagerfanta\Twig\View\TwigView(($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), '@BabDevPagerfanta/default.html.twig'));

        return $instance;
    }
}
