<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayPalOrderCompleteProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\PayPalPlugin\Processor\PayPalOrderCompleteProcessor' shared service.
     *
     * @return \Sylius\PayPalPlugin\Processor\PayPalOrderCompleteProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Processor/PayPalOrderCompleteProcessor.php';

        return $container->services['Sylius\\PayPalPlugin\\Processor\\PayPalOrderCompleteProcessor'] = new \Sylius\PayPalPlugin\Processor\PayPalOrderCompleteProcessor(($container->privates['Sylius\\PayPalPlugin\\Manager\\PaymentStateManagerInterface'] ?? $container->load('getPaymentStateManagerInterfaceService')));
    }
}
