<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayum_StaticRegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'payum.static_registry' shared service.
     *
     * @return \Payum\Core\Bridge\Symfony\ContainerAwareRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Registry/GatewayRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Registry/GatewayFactoryRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Registry/StorageRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Registry/RegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Registry/AbstractRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Bridge/Symfony/ContainerAwareRegistry.php';

        $container->services['payum.static_registry'] = $instance = new \Payum\Core\Bridge\Symfony\ContainerAwareRegistry([], ['App\\Entity\\Order\\Order' => 'payum.storage.app_entity_order_order', 'App\\Entity\\Payment\\Payment' => 'payum.storage.app_entity_payment_payment'], []);

        $instance->setContainer($container);

        return $instance;
    }
}
