<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefundOrderActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\PayPalPlugin\Controller\Webhook\RefundOrderAction' shared service.
     *
     * @return \Sylius\PayPalPlugin\Controller\Webhook\RefundOrderAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Controller/Webhook/RefundOrderAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Provider/PayPalRefundDataProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Provider/PayPalRefundDataProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Api/GenericApiInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Api/GenericApi.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/Client.php';

        return $container->services['Sylius\\PayPalPlugin\\Controller\\Webhook\\RefundOrderAction'] = new \Sylius\PayPalPlugin\Controller\Webhook\RefundOrderAction(($container->services['SM\\Factory\\FactoryInterface'] ?? $container->getFactoryInterfaceService()), ($container->privates['Sylius\\PayPalPlugin\\Provider\\PaymentProviderInterface'] ?? $container->load('getPaymentProviderInterfaceService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), new \Sylius\PayPalPlugin\Provider\PayPalRefundDataProvider(($container->privates['Sylius\\PayPalPlugin\\Api\\CacheAuthorizeClientApiInterface'] ?? $container->load('getCacheAuthorizeClientApiInterfaceService')), new \Sylius\PayPalPlugin\Api\GenericApi(($container->privates['sylius.http_client'] ?? ($container->privates['sylius.http_client'] = new \GuzzleHttp\Client()))), ($container->privates['Sylius\\PayPalPlugin\\Provider\\PayPalPaymentMethodProviderInterface'] ?? $container->load('getPayPalPaymentMethodProviderInterfaceService'))));
    }
}
