<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Listener_CartBlamerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.listener.cart_blamer' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\EventListener\CartBlamerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/EventListener/CartBlamerListener.php';

        return $container->services['sylius.listener.cart_blamer'] = new \Sylius\Bundle\CoreBundle\EventListener\CartBlamerListener(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['sylius.context.cart'] ?? $container->getSylius_Context_CartService()));
    }
}
