<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Api_UploadAvatarImageActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.api.upload_avatar_image_action' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Controller\UploadAvatarImageAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Controller/UploadAvatarImageAction.php';

        return $container->services['sylius.api.upload_avatar_image_action'] = new \Sylius\Bundle\ApiBundle\Controller\UploadAvatarImageAction(($container->services['sylius.factory.avatar_image'] ?? ($container->services['sylius.factory.avatar_image'] = new \Sylius\Component\Resource\Factory\Factory('Sylius\\Component\\Core\\Model\\AvatarImage'))), ($container->services['sylius.repository.avatar_image'] ?? $container->load('getSylius_Repository_AvatarImageService')), ($container->services['sylius.image_uploader'] ?? $container->load('getSylius_ImageUploaderService')), ($container->privates['api_platform.iri_converter'] ?? $container->getApiPlatform_IriConverterService()));
    }
}
