<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Controller_UpdateProductTaxonPositionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.controller.update_product_taxon_position' shared service.
     *
     * @return \Sylius\Bundle\AdminApiBundle\Controller\ProductTaxonPositionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminApiBundle/Controller/ProductTaxonPositionController.php';

        return $container->services['sylius.controller.update_product_taxon_position'] = new \Sylius\Bundle\AdminApiBundle\Controller\ProductTaxonPositionController(($container->services['sylius.repository.product_taxon'] ?? $container->load('getSylius_Repository_ProductTaxonService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
