<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Api_CollectionDataProvider_ShippingMethodsAvailableForOrderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.api.collection_data_provider.shipping_methods_available_for_order' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\DataProvider\CartShippingMethodsSubresourceDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataProvider/RestrictedDataProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/DataProvider/CartShippingMethodsSubresourceDataProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/View/Factory/CartShippingMethodFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/View/Factory/CartShippingMethodFactory.php';

        return $container->privates['sylius.api.collection_data_provider.shipping_methods_available_for_order'] = new \Sylius\Bundle\ApiBundle\DataProvider\CartShippingMethodsSubresourceDataProvider(($container->services['sylius.repository.order'] ?? $container->getSylius_Repository_OrderService()), ($container->services['sylius.repository.shipment'] ?? $container->load('getSylius_Repository_ShipmentService')), ($container->services['sylius.shipping_methods_resolver'] ?? $container->getSylius_ShippingMethodsResolverService()), ($container->services['sylius.registry.shipping_calculator'] ?? $container->load('getSylius_Registry_ShippingCalculatorService')), new \Sylius\Bundle\ApiBundle\View\Factory\CartShippingMethodFactory());
    }
}
