<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_SectionResolver_UriBasedSectionResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.section_resolver.uri_based_section_resolver' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\SectionResolver\UriBasedSectionProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/SectionResolver/SectionProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/SectionResolver/UriBasedSectionProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/SectionResolver/UriBasedSectionResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/SectionResolver/AdminUriBasedSectionResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminApiBundle/SectionResolver/AdminApiUriBasedSectionResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/SectionResolver/ShopUriBasedSectionResolver.php';

        return $container->services['sylius.section_resolver.uri_based_section_resolver'] = new \Sylius\Bundle\CoreBundle\SectionResolver\UriBasedSectionProvider(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), [0 => ($container->services['sylius.section_resolver.admin_uri_based_section_resolver'] ?? ($container->services['sylius.section_resolver.admin_uri_based_section_resolver'] = new \Sylius\Bundle\AdminBundle\SectionResolver\AdminUriBasedSectionResolver('/admin'))), 1 => ($container->services['sylius.section_resolver.admin_api_uri_based_section_resolver'] ?? ($container->services['sylius.section_resolver.admin_api_uri_based_section_resolver'] = new \Sylius\Bundle\AdminApiBundle\SectionResolver\AdminApiUriBasedSectionResolver('/api'))), 2 => ($container->services['sylius.section_resolver.shop_uri_based_section_resolver'] ?? ($container->services['sylius.section_resolver.shop_uri_based_section_resolver'] = new \Sylius\Bundle\ShopBundle\SectionResolver\ShopUriBasedSectionResolver()))]);
    }
}
