<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_OrderProcessing_OrderPaymentProcessor_CheckoutService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.order_processing.order_payment_processor.checkout' shared service.
     *
     * @return \Sylius\PayPalPlugin\Processor\OrderPaymentProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Order/Processor/OrderProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Processor/OrderPaymentProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/OrderProcessing/OrderPaymentProcessor.php';

        return $container->services['sylius.order_processing.order_payment_processor.checkout'] = new \Sylius\PayPalPlugin\Processor\OrderPaymentProcessor(new \Sylius\Component\Core\OrderProcessing\OrderPaymentProcessor(($container->services['sylius.order_payment_provider'] ?? $container->load('getSylius_OrderPaymentProviderService')), 'cart'), ($container->services['SM\\Factory\\FactoryInterface'] ?? $container->getFactoryInterfaceService()));
    }
}
