<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Form_ChoiceList_Loader_LazyCustomerLoaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.form.choice_list.loader.lazy_customer_loader' shared service.
     *
     * @return \Sylius\Bundle\AdminApiBundle\Form\ChoiceList\Loader\LazyCustomerLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/ChoiceList/Loader/ChoiceLoaderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminApiBundle/Form/ChoiceList/Loader/LazyCustomerLoader.php';

        return $container->services['sylius.form.choice_list.loader.lazy_customer_loader'] = new \Sylius\Bundle\AdminApiBundle\Form\ChoiceList\Loader\LazyCustomerLoader(($container->services['sylius.repository.customer'] ?? $container->load('getSylius_Repository_CustomerService')));
    }
}
