<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Api_DataPersister_AddressService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.api.data_persister.address' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\DataPersister\AddressDataPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/DataPersister/AddressDataPersister.php';

        return $container->privates['sylius.api.data_persister.address'] = new \Sylius\Bundle\ApiBundle\DataPersister\AddressDataPersister(($container->privates['api_platform.doctrine.orm.data_persister'] ?? $container->load('getApiPlatform_Doctrine_Orm_DataPersisterService')), ($container->services['sylius.context.customer'] ?? $container->getSylius_Context_CustomerService()));
    }
}
