<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Listener_UserCartRecalculationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.listener.user_cart_recalculation' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\EventListener\UserCartRecalculationListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/EventListener/UserCartRecalculationListener.php';

        return $container->services['sylius.listener.user_cart_recalculation'] = new \Sylius\Bundle\CoreBundle\EventListener\UserCartRecalculationListener(($container->services['sylius.context.cart'] ?? $container->getSylius_Context_CartService()), ($container->services['sylius.order_processing.order_processor'] ?? $container->load('getSylius_OrderProcessing_OrderProcessorService')));
    }
}
