<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_ShippingCalculator_PerUnitRateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.shipping_calculator.per_unit_rate' shared service.
     *
     * @return \Sylius\Component\Core\Shipping\Calculator\PerUnitRateCalculator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Shipping/Calculator/CalculatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Shipping/Calculator/PerUnitRateCalculator.php';

        return $container->services['sylius.shipping_calculator.per_unit_rate'] = new \Sylius\Component\Core\Shipping\Calculator\PerUnitRateCalculator();
    }
}
