<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Api_Validator_PromotionCouponEligibilityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.api.validator.promotion_coupon_eligibility' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Validator\Constraints\PromotionCouponEligibilityValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Validator/Constraints/PromotionCouponEligibilityValidator.php';

        return $container->privates['sylius.api.validator.promotion_coupon_eligibility'] = new \Sylius\Bundle\ApiBundle\Validator\Constraints\PromotionCouponEligibilityValidator(($container->services['sylius.repository.promotion_coupon'] ?? $container->load('getSylius_Repository_PromotionCouponService')), ($container->services['sylius.repository.order'] ?? $container->getSylius_Repository_OrderService()), ($container->services['sylius.promotion_eligibility_checker'] ?? $container->load('getSylius_PromotionEligibilityCheckerService')), ($container->services['sylius.promotion_coupon_eligibility_checker'] ?? $container->load('getSylius_PromotionCouponEligibilityCheckerService')));
    }
}
