<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Api_ProductSlugEventSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.api.product_slug_event_subscriber' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\EventSubscriber\ProductSlugEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/EventSubscriber/ProductSlugEventSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Product/Generator/SlugGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Product/Generator/SlugGenerator.php';

        return $container->privates['sylius.api.product_slug_event_subscriber'] = new \Sylius\Bundle\ApiBundle\EventSubscriber\ProductSlugEventSubscriber(($container->services['sylius.generator.slug'] ?? ($container->services['sylius.generator.slug'] = new \Sylius\Component\Product\Generator\SlugGenerator())));
    }
}
