<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Factory_ApiRefreshTokenService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.factory.api_refresh_token' shared service.
     *
     * @return \Sylius\Component\Resource\Factory\Factory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sylius.factory.api_refresh_token'] = new \Sylius\Component\Resource\Factory\Factory('App\\Entity\\AdminApi\\RefreshToken');
    }
}
