<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSymfonyStyleFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory' shared autowired service.
     *
     * @return \Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symplify/package-builder/src/Console/Style/SymfonyStyleFactory.php';

        return $container->services['Symplify\\PackageBuilder\\Console\\Style\\SymfonyStyleFactory'] = new \Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory();
    }
}
