<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Listener_Api_AddToCartService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.listener.api.add_to_cart' shared service.
     *
     * @return \Sylius\Bundle\AdminApiBundle\EventListener\CartChangeListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminApiBundle/EventListener/CartChangeListener.php';

        return $container->services['sylius.listener.api.add_to_cart'] = new \Sylius\Bundle\AdminApiBundle\EventListener\CartChangeListener(($container->services['sylius.order_processing.order_processor'] ?? $container->load('getSylius_OrderProcessing_OrderProcessorService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
