<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authentication_Listener_FosOauthServer_ApiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.authentication.listener.fos_oauth_server.api' shared service.
     *
     * @return \FOS\OAuthServerBundle\Security\Firewall\OAuthListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/oauth-server-bundle/Security/Firewall/OAuthListener.php';

        return $container->privates['security.authentication.listener.fos_oauth_server.api'] = new \FOS\OAuthServerBundle\Security\Firewall\OAuthListener(($container->services['security.token_storage'] ?? $container->getSecurity_TokenStorageService()), ($container->privates['security.authentication.manager'] ?? $container->getSecurity_Authentication_ManagerService()), ($container->privates['fos_oauth_server.server'] ?? $container->load('getFosOauthServer_ServerService')));
    }
}
