<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Api_GetConfigurationActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.api.get_configuration_action' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Controller\Payment\GetPaymentConfiguration
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Controller/Payment/GetPaymentConfiguration.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Provider/CompositePaymentConfigurationProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Provider/CompositePaymentConfigurationProvider.php';

        return $container->services['sylius.api.get_configuration_action'] = new \Sylius\Bundle\ApiBundle\Controller\Payment\GetPaymentConfiguration(($container->services['sylius.repository.payment'] ?? $container->load('getSylius_Repository_PaymentService')), new \Sylius\Bundle\ApiBundle\Provider\CompositePaymentConfigurationProvider(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['Sylius\\PayPalPlugin\\ApiPlatform\\PayPalPayment'] ?? $container->load('getPayPalPaymentService'));
        }, 1)));
    }
}
