<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Api_DataPersister_ShippingMethodService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.api.data_persister.shipping_method' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\DataPersister\ShippingMethodDataPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/DataPersister/ShippingMethodDataPersister.php';

        return $container->privates['sylius.api.data_persister.shipping_method'] = new \Sylius\Bundle\ApiBundle\DataPersister\ShippingMethodDataPersister(($container->privates['api_platform.doctrine.orm.data_persister'] ?? $container->load('getApiPlatform_Doctrine_Orm_DataPersisterService')));
    }
}
