<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Validator_UniqueReviewerEmailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.validator.unique_reviewer_email' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Validator\Constraints\UniqueReviewerEmailValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Validator/Constraints/UniqueReviewerEmailValidator.php';

        return $container->services['sylius.validator.unique_reviewer_email'] = new \Sylius\Bundle\CoreBundle\Validator\Constraints\UniqueReviewerEmailValidator(($container->services['sylius.repository.shop_user'] ?? $container->load('getSylius_Repository_ShopUserService')), ($container->services['security.token_storage'] ?? $container->getSecurity_TokenStorageService()), ($container->services['security.authorization_checker'] ?? $container->getSecurity_AuthorizationCheckerService()));
    }
}
