<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authentication_Provider_Rememberme_ShopService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.authentication.provider.rememberme.shop' shared service.
     *
     * @return \Symfony\Component\Security\Core\Authentication\Provider\RememberMeAuthenticationProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authentication/Provider/AuthenticationProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authentication/Provider/RememberMeAuthenticationProvider.php';

        return $container->privates['security.authentication.provider.rememberme.shop'] = new \Symfony\Component\Security\Core\Authentication\Provider\RememberMeAuthenticationProvider(($container->privates['SyliusLabs\\Polyfill\\Symfony\\Security\\Core\\User\\UserChecker'] ?? $container->load('getUserCheckerService')), $container->getEnv('APP_SECRET'), 'shop');
    }
}
