<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Form_Extension_Type_ApiOrderItemService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.form.extension.type.api_order_item' shared service.
     *
     * @return \Sylius\Bundle\AdminApiBundle\Form\Type\OrderItemType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminApiBundle/Form/Type/OrderItemType.php';

        return $container->services['sylius.form.extension.type.api_order_item'] = new \Sylius\Bundle\AdminApiBundle\Form\Type\OrderItemType(($container->services['sylius.repository.product_variant'] ?? $container->load('getSylius_Repository_ProductVariantService')));
    }
}
