<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Form_Type_ApiProductVariantService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.form.type.api_product_variant' shared service.
     *
     * @return \Sylius\Bundle\AdminApiBundle\Form\Type\ProductVariantType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminApiBundle/Form/Type/ProductVariantType.php';

        return $container->services['sylius.form.type.api_product_variant'] = new \Sylius\Bundle\AdminApiBundle\Form\Type\ProductVariantType();
    }
}
