<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Grid_ProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.grid.provider' shared service.
     *
     * @return \Sylius\Component\Grid\Provider\ArrayGridProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/grid-bundle/src/Component/Provider/GridProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/grid-bundle/src/Component/Provider/ArrayGridProvider.php';

        return $container->services['sylius.grid.provider'] = new \Sylius\Component\Grid\Provider\ArrayGridProvider(($container->services['sylius.grid.array_to_definition_converter'] ?? $container->load('getSylius_Grid_ArrayToDefinitionConverterService')), $container->parameters['sylius.grids_definitions']);
    }
}
