<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Api_CollectionDataProvider_CustomerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.api.collection_data_provider.customer' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\DataProvider\CustomerItemDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataProvider/RestrictedDataProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/DataProvider/CustomerItemDataProvider.php';

        return $container->privates['sylius.api.collection_data_provider.customer'] = new \Sylius\Bundle\ApiBundle\DataProvider\CustomerItemDataProvider(($container->privates['sylius.api.context.user'] ?? $container->getSylius_Api_Context_UserService()), ($container->services['sylius.repository.customer'] ?? $container->load('getSylius_Repository_CustomerService')));
    }
}
