<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Controller_ShowAvailableShippingMethodsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.controller.show_available_shipping_methods' shared service.
     *
     * @return \Sylius\Bundle\AdminApiBundle\Controller\ShowAvailableShippingMethodsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminApiBundle/Controller/ShowAvailableShippingMethodsController.php';

        return $container->services['sylius.controller.show_available_shipping_methods'] = new \Sylius\Bundle\AdminApiBundle\Controller\ShowAvailableShippingMethodsController(($container->services['SM\\Factory\\FactoryInterface'] ?? $container->getFactoryInterfaceService()), ($container->services['sylius.repository.order'] ?? $container->getSylius_Repository_OrderService()), ($container->services['sylius.shipping_methods_resolver'] ?? $container->getSylius_ShippingMethodsResolverService()), ($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->services['sylius.registry.shipping_calculator'] ?? $container->load('getSylius_Registry_ShippingCalculatorService')));
    }
}
