<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Api_DataPersister_AdminUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.api.data_persister.admin_user' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\DataPersister\AdminUserDataPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/DataPersister/AdminUserDataPersister.php';

        return $container->privates['sylius.api.data_persister.admin_user'] = new \Sylius\Bundle\ApiBundle\DataPersister\AdminUserDataPersister(($container->privates['api_platform.doctrine.orm.data_persister'] ?? $container->load('getApiPlatform_Doctrine_Orm_DataPersisterService')), ($container->services['security.token_storage'] ?? $container->getSecurity_TokenStorageService()), ($container->services['sylius.security.password_updater'] ?? $container->load('getSylius_Security_PasswordUpdaterService')));
    }
}
