<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Listener_EmailUpdaterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.listener.email_updater' shared service.
     *
     * @return \Sylius\Bundle\ShopBundle\EventListener\CustomerEmailUpdaterListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/EventListener/CustomerEmailUpdaterListener.php';

        return $container->services['sylius.listener.email_updater'] = new \Sylius\Bundle\ShopBundle\EventListener\CustomerEmailUpdaterListener(($container->services['sylius.shop_user.token_generator.email_verification'] ?? $container->load('getSylius_ShopUser_TokenGenerator_EmailVerificationService')), ($container->services['Sylius\\Component\\Channel\\Context\\ChannelContextInterface'] ?? $container->getChannelContextInterfaceService()), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->services['session'] ?? $container->getSessionService()), ($container->services['sylius.section_resolver.uri_based_section_resolver'] ?? $container->load('getSylius_SectionResolver_UriBasedSectionResolverService')));
    }
}
