<?php

namespace Container2oRP5bu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTopologicalVersionComparatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'SyliusLabs\DoctrineMigrationsExtraBundle\Comparator\TopologicalVersionComparator' shared service.
     *
     * @return \SyliusLabs\DoctrineMigrationsExtraBundle\Comparator\TopologicalVersionComparator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/Comparator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius-labs/doctrine-migrations-extra-bundle/src/Comparator/TopologicalVersionComparator.php';

        return $container->privates['SyliusLabs\\DoctrineMigrationsExtraBundle\\Comparator\\TopologicalVersionComparator'] = new \SyliusLabs\DoctrineMigrationsExtraBundle\Comparator\TopologicalVersionComparator(['Sylius\\PayPalPlugin\\Migrations' => [0 => 'Sylius\\Bundle\\CoreBundle\\Migrations'], 'Sylius\\Bundle\\AdminApiBundle\\Migrations' => [0 => 'Sylius\\Bundle\\CoreBundle\\Migrations'], 'Sylius\\Bundle\\CoreBundle\\Migrations' => [], 'App\\Migrations' => []]);
    }
}
